/* Run with Playwright installed; optional CHROMIUM_EXECUTABLE_PATH for a system browser. */
const assert=require('node:assert/strict');
const path=require('node:path');
const fs=require('node:fs');
const os=require('node:os');
const {pathToFileURL}=require('node:url');
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?path.join(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES,'playwright'):'playwright');
(async()=>{
 const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_EXECUTABLE_PATH?{executablePath:process.env.CHROMIUM_EXECUTABLE_PATH,args:['--no-sandbox','--disable-gpu','--disable-software-rasterizer','--no-zygote','--single-process']}:{})});
 const page=await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 const file=pathToFileURL(path.resolve(__dirname,'../index.html')).href;
 const click=s=>page.locator(s).click();
 const setRange=(s,v)=>page.locator(s).evaluate((e,v)=>{e.value=v;e.dispatchEvent(new Event('input',{bubbles:true}));},v);
 try {
  await page.goto(file);
  assert.equal(await page.locator('#kpi-ontime').textContent(),'—');
  assert.equal(await page.locator('#source-count').textContent(),'12 départs · 6 retours');
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await click('[data-view="reglages"]');assert.equal(await page.locator('#staff-magasin').isDisabled(),true);
  await setRange('#staff-prepa','19');
  await click('#btn-play');await page.waitForTimeout(400);await click('#btn-play');
  assert.equal(await page.locator('#staff-prepa').isDisabled(),true);
  const clock=await page.locator('#horloge').textContent();await page.waitForTimeout(150);assert.equal(await page.locator('#horloge').textContent(),clock);
  await click('[data-view="vols"]');assert.equal(await page.locator('#flight-rows tr').count(),12);
  await page.locator('#flight-search').fill('NO-MATCH');assert.match(await page.locator('#flight-rows').textContent(),/Aucun départ/);
  await page.locator('#flight-search').fill('');
  await click('[data-view="plan"]');await page.locator('#zone-picker').selectOption('prepa');assert.match(await page.locator('#goulot-info').textContent(),/MONTAGE/);
  await click('#btn-edit');assert.equal(await page.locator('#btn-play').isDisabled(),true);
  await page.locator('[data-action=select][data-zone=cuisine]').click();
  await page.locator('#pe-x').fill('1910');await page.locator('#pe-x').press('Tab');
  await click('#pe-convert');await click('#edit-done');
  const geom=await page.evaluate(()=>Object.fromEntries(JSON.parse(localStorage.getItem('orly-plan-v3')).zones.map(z=>[z.id,z])));
  assert.equal(geom.cuisine.x,1910);assert.equal(geom.cuisine.approx,true);assert.equal(geom.cuisine.pts.length,4);
  await page.reload();assert.equal(await page.evaluate(()=>Object.fromEntries(JSON.parse(localStorage.getItem('orly-plan-v3')).zones.map(z=>[z.id,z])).cuisine.x),1910);
  await click('[data-view="reglages"]');
  await page.locator('#imp-vols').setInputFiles({name:'invalid.csv',mimeType:'text/csv',buffer:Buffer.from('FlightId,Qty\n1,100')});
  await page.waitForFunction(()=>document.getElementById('import-report').classList.contains('error'));
  assert.match(await page.locator('#source-count').textContent(),/12 départs/);
  const header='vol_id,compagnie,type_avion,sens,heure_std,heure_sta,nb_BC,nb_PC,nb_YC\n';
  await page.locator('#imp-vols').setInputFiles({name:'test.csv',mimeType:'text/csv',buffer:Buffer.from(header+'<img src=x>,TX,A350,DEP,05:00,,1,2,100')});
  await page.waitForFunction(()=>document.getElementById('source-label').textContent==='test.csv');
  await click('[data-view="vols"]');assert.equal(await page.locator('#flight-rows img').count(),0);assert.match(await page.locator('#flight-rows').textContent(),/<img src=x>/);
  assert.equal(await page.locator('#kpi-ontime').textContent(),'0 %');assert.equal(await page.locator('#kpi-overdue').textContent(),'1');
  await click('[data-view="reglages"]');await setRange('#staff-appros','0');await setRange('#vitesse','120');
  await click('#btn-play');await page.waitForFunction(()=>document.getElementById('run-state').textContent==='Terminé',{},{timeout:20000});
  assert.equal(await page.locator('#kpi-overdue').textContent(),'1');assert.equal(await page.locator('#kpi-ontime').textContent(),'0 %');
  await click('#snap-a');assert.match(await page.locator('#compare').textContent(),/23:00/);
  const downloaded=page.waitForEvent('download');await click('#btn-export');const download=await downloaded;
  const result=JSON.parse(fs.readFileSync(await download.path(),'utf8'));assert.equal(result.modelStatus,'demonstration_non_calibree');assert.equal(result.vols[0].retard,null);assert.equal(result.kpis.overdue,1);
  await click('[data-view="reglages"]');await click('#restore-demo');await click('[data-view="plan"]');
  await page.evaluate(()=>{localStorage.removeItem('orly-zones');localStorage.removeItem('orly-plan-v3');});await page.reload();
  await page.screenshot({path:path.join(os.tmpdir(),'ory-interface-desktop.png'),fullPage:true});
  await click('#btn-theme');assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');
  await page.screenshot({path:path.join(os.tmpdir(),'ory-interface-dark.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await page.screenshot({path:path.join(os.tmpdir(),'ory-interface-mobile.png'),fullPage:true});
  await click('[data-view="vols"]');assert.equal(await page.locator('#flight-rows tr').count(),12);
  assert.deepEqual(errors,[]);
  console.log('Browser smoke passed: navigation, controls, pause, editor persistence, CSV rejection/import, escaping, overdue completion, snapshots, export, dark/mobile layouts.');
 } finally {await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
